
function onInit()
	-- Used to auto populate skills before the skills tab has been opened.
	Debug.console("charsheet_init.lua: inInit");
	local skillsnode = window.getDatabaseNode().createChild("skills");
	if skillsnode then
		local skillautocreated = skillsnode.createChild("..skillsautogenerated", "number");
		if skillautocreated.getValue() ~= 1 then
			Debug.console("charsheet_init.lua: Skills haven't been created - creating...");
			for k,v in pairs(DataCommon.basicskilldata) do
				local skillnode = skillsnode.createChild();
				skillnode.createChild("name","string").setValue(k);					
				skillnode.createChild("characteristic","string").setValue(v.characteristic);
				skillnode.createChild("description","formattedtext").setValue(v.description);
			end
			skillsnode.getChild("..skillsautogenerated").setValue(1);
		else
			Debug.console("charsheet_init.lua: Skills already created.");
		end
	end	

	if skillsnode then
		local knowledgeautocreated = skillsnode.createChild("..skillsknowledgeautogenerated", "number");
		if knowledgeautocreated.getValue() ~= 1 then
			for k,v in pairs(DataCommon.knowledgeskilldata) do
				local skillnode = skillsnode.createChild();
				skillnode.createChild("name","string").setValue(k);					
				skillnode.createChild("characteristic","string").setValue(v.characteristic);
				skillnode.createChild("description","formattedtext").setValue(v.description);
				skillnode.createChild("knowledge","number").setValue(v.knowledge);
			end
			if PreferenceManager.getValue("version_ageofrebellion") then
				for k,v in pairs(DataCommon.ageofrebellion_skilldata) do
					local skillnode = skillsnode.createChild();
					skillnode.createChild("name","string").setValue(k);					
					skillnode.createChild("characteristic","string").setValue(v.characteristic);
					skillnode.createChild("description","formattedtext").setValue(v.description);
					skillnode.createChild("knowledge","number").setValue(v.knowledge);
				end
			end								
			skillsnode.getChild("..skillsknowledgeautogenerated").setValue(1);
		end
	end	

	if skillsnode then
		local combatautocreated = skillsnode.createChild("..skillscombatautogenerated", "number");
		if combatautocreated.getValue() ~= 1 then
			for k,v in pairs(DataCommon.combatskilldata) do
				local skillnode = skillsnode.createChild();
				skillnode.createChild("name","string").setValue(k);					
				skillnode.createChild("characteristic","string").setValue(v.characteristic);
				skillnode.createChild("description","formattedtext").setValue(v.description);
				skillnode.createChild("advanced","number").setValue(v.advanced);
			end
			if PreferenceManager.getValue("version_forceanddestiny") then
				for k,v in pairs(DataCommon.forceanddestiny_skilldata) do
					local skillnode = skillsnode.createChild();
					skillnode.createChild("name","string").setValue(k);					
					skillnode.createChild("characteristic","string").setValue(v.characteristic);
					skillnode.createChild("description","formattedtext").setValue(v.description);
					skillnode.createChild("advanced","number").setValue(v.advanced);
				end
			end
			skillsnode.getChild("..skillscombatautogenerated").setValue(1);
		end
	end
end